<div class="container-fluid">
            <a id="logoInicio" href="index.php">
                <img alt="hexagon" class="logo" src="img/hexagon.png" />
                LENGUAJES
            </a>
        </div>

        <nav class="navbar navbar-inverse">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">
                        <li class="active"><a href="index.php">INICIO</a></li>
                        <li><a href="java.php">JAVA</a></li>
                        <li><a href="javascript.php">JAVASCRIPT</a></li>
                    </ul>
                </div>
            </div>
        </nav>